### ISSUE TITLE
Support of pickle serialization of Cython objects in python API

### ISSUE THREAD

**Issue by ghost** [Cantera/enhancements#10]
Serialization is used to transfer objects between processes, nodes, or even between windows and linux. It is also widely used in parallel program design. However, the cython objects such as ct.Solution and ct.Reaction cannot be serialized due to lack of serialization support. 

refer to https://snorfalorpagus.net/blog/2016/04/16/pickling-cython-classes/. It seems  simple to support serialization in python using pickle.

I tried to use monkey patching to assign `__reduce__()` method to Reaction object, but it is forbidden by python. So I think it is better to be implemented in cython layer. 

Think about this scenario: I can save the Solution object or even FreeFlame object to a *.pkl file in Linux and send it to someone or forum. The receiver can simply load it in Windows and help me to check what is going wrong.

**Comment by ischoegl** [comment]
Pickle support will be at least *feasible* once YAML serialization is implemented (see #11). As mentioned above, Cantera/cantera#692 illustrates a blueprint that is based on artifacts from (soon to be deprecated) CTI/XML import. The same can be easily accomplished once YAML emitters of various Cantera objects - as well as the entire `Solution` object itself - become available.

There are caveats about parts of Cantera using multiple threads already internally (e.g. via Intel MKL), which, however, can be alleviated by setting the environment variable `OMP_NUM_THREADS=1` (this works at least on Linux).
