### ISSUE TITLE
Real gas EOS with 1-D flame solutions 

### ISSUE THREAD

**Issue by RSuryaNarayan** [Cantera/enhancements#109]
Hello everyone, 

This is a feature request to enable supercritical 1-D flame solutions in Cantera. There have been many such requests/queries brought to the table in the user's forum. Most of the questions have been directed towards modified transport/high-pressure transport along with real gas EOS solutions instead of the ideal gas law for 1-D flame solutions. 

This feature could possibly require a complete re-implementation of the 1-D flame. The API could look something like this: 

```
f.solution(eos= 'PR/SRK/Ideal', loglevel=1, ...)
```
PR- Peng-Robinson
SRK - Soave-Redlich-Kwong
Ideal- Ideal gas EOS

Thanks a lot!

**Comment by speth** [comment]
Completed by @gkogekar in Cantera/cantera#1079.
