### ISSUE TITLE
Tsang falloff format

### ISSUE THREAD

**Issue by mefuller** [Cantera/enhancements#113]
**Abstract**

Add support for defining falloff rates via Wing Tsang's falloff expression (see e.g doi 10.1063/1.555890).
The value of F_cent is explicitly defined as `F_cent = A + B*T` (where B is often zero) and the falloff factor, `F`, is calculated from `F_cent` identically with the expressions of Troe.
Further, the converter programs should be updated to recognize and convert rates provided in this format.

**Motivation**

Adding this support allows for use of rates tabulated in the databases authored by Tsang and co-workers without refitting.
Refitting the Tsang parameters to Troe formalism is unsatisfying as the `F_cent` values specified by Tsang are constant or linear with temperature. Troe's formalism (`F_cent = (1-A)exp(-T/T_3) + Aexp(-T/T_1) + exp(-T_2/T)`) has a fundamentally different functional form, which lends itself only to tedious and inexact mapping of Tsang's form.

Further, updating the conversion scripts for import CHEMKIN mechanisms which contain rates in this format will improve the ability of Cantera users to make direct comparisons with previously published mechanisms which contain Tsang falloffs.

The overall changes required are fairly minimal as they should be analogous to the existing functions addressing Troe fits.
Only user-specified input parameters and calculation of `F_cent` need be updated.

**Description**
Please see the draft PR: https://github.com/Cantera/cantera/pull/1090 for current implementation of the proposed changes.

**Alternatives**
Users could manually refit the Troe falloff parameters from the Tsang values.
This is a poor alternative as it would be tedious and inexact as the functional forms of the expressions for `F_cent` differ in their dependence on temperature (exponential for Troe, linear for Tsang), preventing proper comparisonor use of the rates as published by Tsang.

**References**
Current draft PR: https://github.com/Cantera/cantera/pull/1090
Example of Tsang database: https://doi.org/10.1063/1.555890
Example of Chemkin implementation of Tsang format (see mechanism in supplemental materials): https://doi.org/10.1016/j.combustflame.2011.02.010

**Comment by ischoegl** [comment]
~Closed via Cantera/cantera#1090~

While the enhancement (Cantera/cantera#1090) is merged, this request should likely remain open until the science section is updated.

**Comment by bryanwweber** [comment]
Closed by https://github.com/Cantera/cantera-website/pull/153
