### ISSUE TITLE
Clarify usage of repository

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#12]
At the moment, it is not clear how this repository will be used: will this be a fork of Cantera, that can be rebased/merged in the usual manner, or is this meant to be a repository that collects code compiled against core cantera (e.g. similar to [`ctwrap`](https://github.com/ischoegl/ctwrap)).

Specifically, I have two PR's in the main repository that are stubs (Cantera/cantera#692 and Cantera/cantera#694), which could arguably be moved here as neither is ready to be merged (they depend on ongoing work summarized in issue #11). What would be the proposed mechanism for accomplishing this (i.e. moving the stubs here), while still being able to compile and test as usual? (I admittedly may not be fully aware of the entirety of git features).

**Comment by bryanwweber** [comment]
This repo is currently intended as a issues-only repo for discussion of large-ish changes to Cantera. Check out #9 and the files @speth has added there. The idea is not to have any code in this repo, only discussion. This repo is inspired by NumPy Enhancement Proposals (which are in turn inspired by PEPs): https://numpy.org/neps/index.html

**Comment by ischoegl** [comment]
Sounds good. 

This repo's [README.md](https://github.com/Cantera/enhancements/blob/master/README.md) file is probably work in progress, but hopefully will make this clear eventually.

**Comment by bryanwweber** [comment]
Yes, see the README in #9

**Comment by ischoegl** [comment]
Clearly, work in progress! :+1
