### ISSUE TITLE
Cantera for Ubuntu 22.04

### ISSUE THREAD

**Issue by ste-lor** [Cantera/enhancements#138]
Is Cantera already available for Ubuntu 22.04 (Jammy Jellyfish)?
I tried to install it according to [Cantera installation](https://cantera.org/install/ubuntu-install.html) but get the error "the repository does not have a release file". Is there another way to install it in the meantime or do I just have to wait?

I only recently switch to Ubuntu, but used Cantera under Windows. Very nice tool by the way (y).

**Comment by ste-lor** [comment]
Ok, thanks for the quick reply.

**Comment by bryanwweber** [comment]
@ste-lor As those instructions state, the Ubuntu installer is available for:

> Ubuntu 18.04 (Bionic Beaver), Ubuntu 20.04 (Focal Fossa), Ubuntu 20.10 (Groovy Gorilla), and Ubuntu 21.04 (Hirsute Hippo).

So, no, not 22.04.
