### ISSUE TITLE
Consolidate works cited

### ISSUE THREAD

**Issue by speth** [Cantera/enhancements#145]
**Abstract**

It would be nice to have a consolidated list of references for citations to the literature that describes various models implemented in Cantera. This would encourage consistent use of citations within the documentation without bloating the documentation with duplicated reference information.

**Motivation**

Currently, this is done on a fairly ad-hoc basis, with citations appearing in the documentation for individual C++ classes or methods (e.g. [`MixTransport`](https://cantera.org/documentation/docs-2.5/doxygen/html/d9/d17/classCantera_1_1MixTransport.html#details) or on individual pages within the website's "Science" documentation (e.g. [reactions](https://cantera.org/science/reactions.html#lindemann1922)). Consolidating these references into a single location would make it easier to add citations from more parts of the documentation without having to duplicate information in many places.

**Possible Solutions**

Doxygen supports the [`@cite`](https://www.doxygen.nl/manual/commands.html#cmdcite) command, which can be used to cite references from a Bibtex file and generate a corresponding bibliography.

I have not looked into what options exist for Sphinx, or if there is a way to combine this with the citations from Doxygen. One issue with trying to combine the two would be synchronization (or lack thereof) between the code and website repositories.

**References**

**Comment by ischoegl** [comment]
Cantera/cantera#1550 addresses this for references within C++ docstrings. For website "Science" documentation and other content generated by Sphinx, extensions like `sphinxcontrib-bibtex`  or similar should be able to use a shared `cantera.bib` BibTeX file.
