### ISSUE TITLE
Advanced mixing rules for colliders

### ISSUE THREAD

**Issue by rwest** [Cantera/enhancements#157]
**Abstract**

A placeholder issue before I forget. I couldn't find an existing enhancement issue for this. A talk at the Combustion Symposium, 

> 2A02: Shock tube/laser absorption measurement of the rate constant of the reaction: H2O2 + CO2  2OH + CO2
J. Shao,
R. Choudhary, D.F. Davidson, R.K. Hanson

just showed a huge impact of changing mixing rules (3x difference in concluded reaction rate?) and pointed out that Mike Burke's improved rules are not available in CHEMKIN or Cantera. 

**Motivation**
From https://burke.me.columbia.edu/research-projects/ab-initio-theoretical-studies-reaction-kinetics-mixtures

> The effect of many inert collision partners is essentially always handled via a mixture "rule," which is embedded in reacting flow codes (e.g. CHEMKIN, Cantera) and used to derive collision partner efficiencies from experiments. Our group has found that the most common mixture rule, on which codes and experimental interpretations are based, fails for exactly the mixtures in combustion – with errors up to an order of magnitude. These errors significantly influence predictions of flame speeds, ignition delay times, and other combustion properties as well as experimental interpretations used to derive collision efficiencies. To address these deficiencies, we have been developing new mixture rules that can reliably predict kinetics in mixtures. Once completed, these new mixture rules will enable more accurate treatment of mixture composition effects on kinetics in future reacting flow codes.

* What problem is it trying to solve?
* Who is affected by the change?
* Why is this a good solution?

**Possible Solutions**

A detailed description of the proposed change, if there is a particular implementation that should be considered. This may include examples of how the new feature would be used, intended use cases, and pseudo-code illustrating its use. If any alternative solutions have been considered, list them them and explain why the proposed approach is preferable.

**References**

Links to related Pull Requests, GitHub Issues, Users' Group topics, or other relevant material.

@TheBurkeLab @michaelpburke

**Comment by michaelpburke** [comment]
I would advocate implementing the reduced-pressure mixture rule LMR,R
(described in the attached implementation guide) -- it provides reasonable
accuracy without introducing the added complications of NMR,R.  You can
find a python implementation of it here:
https://github.com/Simple-ape/MixtureRules

**Comment by bryanwweber** [comment]
Hi @michaelpburke! Thanks for the pointer. What's the license of that code? The default without specifying one, at least in the US, is "All rights reserved", meaning we can't include it or use it in Cantera.

The easiest license for us to incorporate is BSD-style, as Cantera is under a similar license. The MIT license is similar and could also work.

**Comment by michaelpburke** [comment]
I would like anyone to be able to use it freely.  Would prefer if they cite
the accompanying paper(s) where they are presented.  Suggestions?

**Comment by ischoegl** [comment]
Hi @michaelpburke ... likewise thanks for the pointer. Will your group submit a PR on this work?

**Comment by bryanwweber** [comment]
@michaelpburke I think the BSD 3-clause license is the most common one, in that case. The text is here: https://opensource.org/licenses/BSD-3-Clause Copy that into a file called `LICENSE` in the root of the repository and add your name(s) and the year 😄 

The first two clauses of the license state:

> must retain the above copyright notice

meaning anyone using the code in their projects must give you credit via the copyright notice.

I'm not sure if there's a general way to enforce people citing the literature (one of the perennial problems with scientific software). Certainly we would do so, but that won't show up in citation counters. More generally, GitHub will process metadata from a file called `CITATION.cff` if you put that into the root of your repository, see here for the docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by michaelpburke** [comment]
I uploaded the license file (I went with the BSD-3 -- thanks for the
suggestion!)

Ingmar, we weren't planning on submitting a PR to Cantera for this.  Should
we?

**Comment by ischoegl** [comment]
@michaelpburke ... it's up to you. Personally, I found that contributing to the main project will ensure that extensions will be supported for the foreseeable future (things don't break as they are continually tested). At the same time, your repo mainly demonstrates an interesting capability, while not being linked to Cantera itself. If you feel that it's important to have the capability integrated with the main code, then a PR with a C++ implementation would be a logical route. Cantera depends on contributions from the community, so this would be very welcome overall.

**Comment by speth** [comment]
The Pull Request for this is now open: Cantera/cantera#1710

**Comment by speth** [comment]
Cantera/cantera#1710 has been merged.
