### ISSUE TITLE
Add option for MixDiffCoeffsMass in 1D flames

### ISSUE THREAD

**Issue by g3bk47** [Cantera/enhancements#195]
Currently, running 1D flames with the mixture-averaged diffusion model computes the species diffusive fluxes (neglecting the correction flux for the sake of brevity) from
$$j_k=-\rho D_k \frac{W_k}{\bar{W}} \frac{\partial X_k}{\partial z},$$
where $`D_k`$ is computed from the `mix_diff_coeffs` function. In many 3D simulation codes, governing equations are solved in terms of species mass fractions and the diffusive flux is computed with respect to the species mass fraction gradients
$$j_k=-\rho D_k^{\rm mass} \frac{\partial Y_k}{\partial z},$$
where $`D_k^{\rm mass}`$ is computed from the `mix_diff_coeffs_mass` function. While both formulations yield similar results, they are not the same. Therefore, I implemented a switch to choose between both formulations (see my branch here: https://github.com/g3bk47/cantera/tree/flame_mix_diff_mass).

There are two reasons why I think this would be a valuable addition to Cantera:

1) Running 1D flames with the mass fraction gradient-based fluxes can be used to generate better validation data for those simulation tools that use the second flux formulation above.
2) There are arguments in the literature why the current flux formulation is more accurate than the mass fraction-based approach, which is why I left the current formulation as the default. However, I recently did a few tests comparing hydrogen-air flames from multicomponent and mixture-averaged solutions. Surprisingly (at least to me), the mass fraction-based mixture-averaged solution matches the multicomponent solution much more closely than the mole fraction gradient one (but maybe this is just a fluke...)
![flamespeeds](https://github.com/Cantera/enhancements/assets/22117927/a37799b2-1c63-4cda-8231-b76c4d66f780)
The script for generating this plot is:  [flamespeeds.txt](https://github.com/Cantera/enhancements/files/14227105/flamespeeds.txt)

The code changes for adding the option of using the mass fraction-based gradient fluxes are quite minimal (https://github.com/g3bk47/cantera/tree/flame_mix_diff_mass). However, I am not too happy with the names of the new functions/properties, as they are not very intuitive (`use_mix_diff_coeffs_mass`). Any other name I can think of is quite verbose, like `flame.switch_to_mass_fraction_gradient_based_fluxes`. Let me know if you have any better ideas or if you have any other comments regarding the code before I open a pull request.

**Comment by speth** [comment]
I think this would be a worthwhile addition. I've always found the mass-fraction based formulation to be more natural, and it's interesting to see that at it might be closer to the multicomponent formulation for some purposes.

I agree that naming is a bit tricky here. One alternative that comes to mind would be to have `diff_coeff_basis` be a property that is set to either the string `mass` or `mole` (while still using a boolean as the internal member variable for efficiency), though I'm not sure that's an improvement over what you already have.

**Comment by g3bk47** [comment]
Merged with https://github.com/Cantera/cantera/commit/66835e2d8d75c8c63f1cca450a8212e984b3bab1
