### ISSUE TITLE
Including the solution of liquid phase kinetics in Cantera

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cantera/enhancements#2]
```
Cantera is a software for solving detailed gas phase kinetics. It also has a 
good framework to implement solution of reactor networks. This specific 
application of cantera would be useful in chemical reactor modeling if it were 
possible in cantera to include liquid phase reactions. 

Thanks,
Ajinkya
```

Original issue reported on code.google.com by `ajinkya....@gmail.com` on 12 Nov 2012 at 10:22

**Comment by speth** [comment]
As of Cantera 3.0, the `BulkKinetics` class can represent reactions in any gas, liquid, or solid phase. And with the introduction of the `ExtensibleRate` class (also in Cantera 3.0), reaction rate parameterizations relevant to liquids can be implemented as needed. So fundamentally, I think this feature now exists. Future enhancements would be implementations of additional thermodynamic models relevant to particular types of liquids, besides the ones already available.

**Comment by BoyangMichael** [comment]
Thanks for the good work! It just remind me of another question. Sorry for using this place to post it... In the `ExtensibleRate` class, is it possible to define a rate expression depending on an "external" variable (not just on T,P)? For example, k = x A exp(-Ea/RT)? Where x is a variable not in the mechanism, but rather a physical variable to model. Thank you very much in advance!

**Comment by speth** [comment]
Generally no, that's not currently possible. I think that would be a different enhancement proposal (which you're welcome to open). Having some concrete use cases would help think through the interface and how it would have to interact with other classes like `ThermoPhase` and `Reactor`.

**Comment by ischoegl** [comment]
I believe you can implement k = x A \exp(-Ea/RT) with a `CustomRate`, see https://cantera.org/dev/python/kinetics.html#customrate

It is not as formalized as `ExtensibleRate`, but may just work (the `lambda` function takes T as an argument, but can depend on other parameters that are in scope; at least if I recall correctly)

**Comment by BoyangMichael** [comment]
Thank you both very much for your help! I will try `CustomRate`.

**Comment by speth** [comment]
I'd like to shift this discussion to https://github.com/Cantera/enhancements/discussions/204.
