### ISSUE TITLE
addReaction produce two different copy of the rate object

### ISSUE THREAD

**Issue by BangShiuh** [Cantera/enhancements#215]
**Abstract**

The below code prints the address of rate objects.

```
    void add(size_t rxn_index, ReactionRate& rate) override {
        m_indices[rxn_index] = m_rxn_rates.size();
        m_rxn_rates.emplace_back(rxn_index, dynamic_cast<RateType&>(rate));
        // Print the address of 'rate' and the address of the corresponding element in m_rxn_rates
        std::cout << "Address of rate: " << &rate << std::endl;
        std::cout << "Address of element in m_rxn_rates: " << &m_rxn_rates.back().second << std::endl;
        m_shared.invalidateCache();
    }
```
It shows that the address is different. This creates issues:
1. Extra memory to store rate data
2. Change of Reaction::rate() does not affect the corresponding element in m_rxn_rates.

This "add" function is called by  `BulkKinetics::addReaction`,
```
    // Add reaction rate to evaluator
    size_t index = m_bulk_types[rtype];
    m_bulk_rates[index]->add(nReactions() - 1, *rate);
```

**Motivation**

Describe the need for the proposed change:

* What problem is it trying to solve?
* Who is affected by the change?
* Why is this a good solution?

**Possible Solutions**

Consider fixing m_rxn_rates.emplace_back(rxn_index, dynamic_cast<RateType&>(rate));

**References**

Links to related Pull Requests, GitHub Issues, Users' Group topics, or other relevant material.

**Comment by BangShiuh** [comment]
@ischoegl @speth I found this issue while implementing the plasma feature.

**Comment by BangShiuh** [comment]
Maybe move this issue to

**Comment by ischoegl** [comment]
@BangShiuh this is by design … see Cantera/cantera#1211 and related discussions. 

This is overall a long-standing design choice. There were some discussions on this topic a couple of years ago but it was never revisited.
