### ISSUE TITLE
Inclusion of alternative radiation models and species

### ISSUE THREAD

**Issue by marina8888** [Cantera/enhancements#218]
**Abstract**

I am considering expanding the capabilities of Cantera for the following: 
- Including NO, NH3, N2O species in the OTM model.
- Look at the possibility of including other calculation models for radiation. 

I'd appreciate your feedback and ideas.

Currently, I have codes to do simple calculations like a lookup to HITRAN database for absorption coefficients and integrations. I am considering the best way to include these and possibly more complex models in Cantera, if there is interest.

**Comment by marina8888** [comment]
I have found a pull request which refactors the radiation model to use yaml files for other gas specification - I will close this request for now.

**Comment by ischoegl** [comment]
@marina8888 ... there definitely is interest, see Cantera/cantera#1799 (as well as the original version Cantera/cantera#965)

**Comment by marina8888** [comment]
@ischoegl thank you for confirming - once I have something usable, I'll check how it works with #1799 and go from there.
