### ISSUE TITLE
Streamline sample folders

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#27]
**Abstract**

Use a single location for samples from various interfaces (C++/Fortran/Python/MATLAB).

**Motivation**

Currently, Python samples are installed into the Cantera package path, i.e.
```
Cantera has been successfully installed.

File locations:

  applications                C:/Users/<user>/cantera\bin
  library files               C:/Users/<user>/cantera\lib
  C++ headers                 C:/Users/<user>/cantera\include
  samples                     C:/Users/<user>/cantera\samples
  data files                  C:/Users/<user>/cantera\data
  Python package (cantera)    C:\Users\<user>\AppData\Local\Continuum\anaconda3\envs\cantera-dev\Lib\site-packages
  Python samples              C:\Users\<user>\AppData\Local\Continuum\anaconda3\envs\cantera-dev\Lib\site-package\cantera\examples
scons: done building targets.
```
which results in an unnecessarily long / inconvenient Python sample path that (depending on OS and installation options) even may be write-protected.

**Possible Solutions**

Move the Python samples to the `samples` folder.

**References**

This affects #22, as a possible solution would be to relocate all `sample` input files to the `sample` folder.

**Comment by speth** [comment]
I'm not sure this is possible, at least for installation of the Python package through either the standalone MSI installer or Conda package. I think such packages have to install all of their data within the Python installation that is hosting them.

**Comment by ischoegl** [comment]
That makes sense, and explains the status quo. Thanks!
