### ISSUE TITLE
Include a units package to clarify values (possibly Python only)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cantera/enhancements#3]
```
After just spending way too much time looking for an error caused by my wrong 
use of units, I suggest including a units package. Thus, you could e.g. 
determine much more easy what gas.viscosity is;)

Possibly, this would make sense for the Python interface only. There are 
several packages available (numericalunits, pint, units). I personally became a 
big fan of pint (https://pint.readthedocs.org).

However, I don't know if the wrapping of the C++ code makes things more 
difficult. It surely is low-priority. But it would still be a cool feature.

```

Original issue reported on code.google.com by `thetruet...@googlemail.com` on 29 Jan 2014 at 9:58

**Comment by bryanwweber** [comment]
From the GSoC idea issue #36:

## Idea

Nearly all calculations in Cantera are done in SI units (K, Pa, kg, kmol), and the units of quantities available to the user are also in SI units. Although this is the most useful general case, it would be helpful if users could input other units to Cantera functions and the conversion to SI is done internally before conducting calculations. This project would implement a wrapper around Cantera classes and/or functions to enable the use of alternative units transparently.

## Difficulty

Medium-Easy

## Required Knowledge

Python

## Mentors

@bryanwweber

**Comment by shrey27tri01** [comment]
> From the GSoC idea issue #36:
> ## Idea
> 
> Nearly all calculations in Cantera are done in SI units (K, Pa, kg, kmol), and the units of quantities available to the user are also in SI units. Although this is the most useful general case, it would be helpful if users could input other units to Cantera functions and the conversion to SI is done internally before conducting calculations. This project would implement a wrapper around Cantera classes and/or functions to enable the use of alternative units transparently.
> ## Difficulty
> 
> Medium-Easy
> ## Required Knowledge
> 
> Python
> ## Mentors
> 
> @bryanwweber 

@bryanwweber I would like to contribute this year in GSoC; would like to implement this idea.

**Comment by BugsBunny0** [comment]
> From the GSoC idea issue #36:
> 
> ## Idea
> Nearly all calculations in Cantera are done in SI units (K, Pa, kg, kmol), and the units of quantities available to the user are also in SI units. Although this is the most useful general case, it would be helpful if users could input other units to Cantera functions and the conversion to SI is done internally before conducting calculations. This project would implement a wrapper around Cantera classes and/or functions to enable the use of alternative units transparently.
> 
> ## Difficulty
> Medium-Easy
> 
> ## Required Knowledge
> Python
> 
> ## Mentors
> @bryanwweber

@bryanwweber Would love to contribute to the project for GSoC.

**Comment by bryanwweber** [comment]
@shrey27tri01 @BugsBunny0 Hello, welcome to Cantera. Please see our wiki page about GSoC 2020 for more information about applying. Thanks for your interest.

**Comment by Arsh0508** [comment]
@bryanwweber sir, I  would love to work on this project for GSoC 2020. I was hoping, if you could kindly guide me on how to proceed with this?

**Comment by bryanwweber** [comment]
@Arsh0508 Please see my previous comment and the links there.

**Comment by Arsh0508** [comment]
@bryanwweber Sir, I was hoping if you could help me get started with it as I'm unable to find the repo where I am supposed to implement the wrapper in.

**Comment by bryanwweber** [comment]
@Arsh0508 the main Cantera repository is at https://github.com/Cantera/cantera. Is that what you needed?

**Comment by Arsh0508** [comment]
@bryanwweber yes sir, thanks a lot!!

**Comment by ischoegl** [comment]
Superseded by #174
