### ISSUE TITLE
Access gas transport properties polynomials

### ISSUE THREAD

**Issue by lavdwall** [Cantera/enhancements#40]
This might not be a real feature request, but I didn't really know where else to ask this.

**Abstract**
Would it be possible to provide access functions to obtain the polynomial fits m_condcoeffs, m_visccoeffs and m_diffcoeffs from the GasTransport class?

**Motivation**
I have developed an OpenFOAM utility to convert Cantera mechanisms, thermo and transport properties to OpenFOAM format. My quick fix around the non-accessible m_condcoeffs, m_visccoeffs and m_diffcoeffs was to make those variables public and compile Cantera from source. However, it would be much easier if there were public C++ access functions, so that everybody who wants to use my code doesn't have to do a Cantera install from source.

**Possible Solutions**
Provide access functions that return m_condcoeffs, m_visccoeffs and m_diffcoeffs in GasTransport.h

**Comment by bryanwweber** [comment]
Hi, thanks for filing an issue here! Since you already have the code working, would you consider making a pull request over at the main code repository?

**Comment by ischoegl** [comment]
This can be closed via Cantera/cantera#817.
