### ISSUE TITLE
Implementation of one-dimensional packed-bed reactor model

### ISSUE THREAD

**Issue by gkogekar** [Cantera/enhancements#43]
**Abstract**

A one-dimensional, steady-state packed-bed reactor model with surface chemistry is being developed. The model solves a system of differential algebraic equations (DAEs) using Sundials package.   

**Required Knowledge**

C++
Sundials Suite

**Comment by speth** [comment]
Is this building off of the work started in Cantera/cantera#575?

**Comment by gkogekar** [comment]
Currently it is a stand-alone, in-house code, which only calls Cantera and uses Sundials separately. But yes, once I start merging my code in Cantera, it may have conflicts with the above pull request.

**Comment by speth** [comment]
I think with the example now merged into the main repository (see https://cantera.org/dev/examples/python/reactors/1D_packed_bed.html) this can be regarded as complete.
