### ISSUE TITLE
Consistent standard reference state properties

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#48]
**Abstract**

The development branch introduces interfaces for standard enthalpies / entropies `h0` and `s0` at reference states for some species thermo classes (e.g. Shomate polynomial, piece-wise Gibbs and HKFT, see [dev Documentation](https://cantera.org/documentation/dev/sphinx/html/yaml/species.html)). It would be great to have standard state properties consistently available at the thermo phase level for illustration purposes.

**Motivation**

In teaching, the concept of standard enthalpies of formation and other standard state properties are central concepts, where quantities are tied to a reference state (e.g. 298 K). While those quantities can already be calculated, the usage is non-intuitive and/or cumbersome, e.g.
```
>>> gas.standard_enthalpies_RT * ct.gas_constant * 298

>>> gas.standard_entropies_R * ct.gas_constant
```
The enhancement request is motivated by teaching in undergraduate classes where students may not have prior exposure to Python and/or Cantera. Standard state properties are one of the first concepts that students encounter.

**Possible Solutions**

Introduce `T0`, `h0`, `s0`, `g0`, etc. (exact nomenclature to be determined) for any thermo phase in C++ `ThermoPhase.h` and overload at least `IdealGasPhase.h`. Create an interface in Python that makes interactions straight-forward.

**References**

Any standard textbook discussing enthalpies of formation, i.e. <img src="https://render.githubusercontent.com/render/math?math=\bar{h}_f^\circ">

**Comment by bryanwweber** [comment]
Why is this closed? It seems useful.

**Comment by ischoegl** [comment]
It’s likely extremely low priority, and not really necessary outside of instruction. I.e. a distraction?

**Comment by bryanwweber** [comment]
The point of this repository (IMO) is to leave issues open that seem useful and require further discussion/implementation. Low priority doesn't mean it would not be useful and something that could be taken on.

**Comment by ischoegl** [comment]
This is certainly an argument, but not everything that may be useful should be actually adopted. If it’s something where the cost of implementation/maintenance is in no relation to the benefit, I believe that pulling the plug early is likely the most appropriate action.
