### ISSUE TITLE
Install via pip

### ISSUE THREAD

**Issue by ma-sadeghi** [Cantera/enhancements#5]
I'm not sure if here's the right place to post a feature request, so sorry about that.

We're thinking of using Cantera to handle mixtures in our pore network simulation package, [OpenPNM](https://github.com/PMEAL/OpenPNM/). The only issue is that Cantera is not `pip`-installable, and we'd like our package to be installed solely using `pip` for convenience. I wonder if you could provide support for `pip`. I'd be happy to contribute myself if that's not on your priority list.

Thanks,
Amin

**Comment by bryanwweber** [comment]
The `multibuild` project might be useful here: https://github.com/matthew-brett/multibuild

**Comment by bryanwweber** [comment]
Work has started on this in the branch here: https://github.com/bryanwweber/cantera/tree/add-pypi-package

**Comment by bryanwweber** [comment]
I've managed to get a wheel build working on my computer 🎉 and I don't think that'll be too hard to generalize to other systems/architectures.

The trickier bit is distributing an `sdist`, a source distribution. Inevitably, we will have to include Cantera's C++ code which will be compiled by the user. After that, there seem to be two main options here:
1) Bundle all our dependencies source code (SUNDIALS, libfmt, etc.)
2) Rely on the user to have these dependencies installed locally before installing Cantera

The advantage of (2) is that the tarball of the sdist will be smaller and easier to generate. The downside is that we have a few version-specific API munging sections that need to know what version of the library is installed, which is a little bit tricky to accomplish. On the other hand, the advantage of (1) is that _everything_ will be built locally by the user, so it is more likely to work together. The downside is a larger tarball and a more complicated `setup.py` to compile everything.

Looking at a few related libraries, CoolProp follows (1) and h5py follows (2). CoolProp has a similar number of dependencies as us, while h5py only depends on libhdf5.

I'm personally leaning towards (1), but thoughts/suggestions are welcome!

**Comment by decaluwe** [comment]
Awesome work, @bryanwweber ! 

I'm pretty much in over my head on the particulars of your above question, but from a user perspective I tend to agree with your lean - option (1) feels like it be less likely to run into problems (again, from my very naive understanding)

**Comment by ischoegl** [comment]
I agree, awesome work! Out of curiosity, what approach does numpy use?

**Comment by bryanwweber** [comment]
> I agree, awesome work! .... Awesome work, @bryanwweber !

Thanks to you both!

> Out of curiosity, what approach does numpy use?

NumPy is a bit of an odd duck, because they have an entire _module_ dedicated to properly building from the sdist (`numpy.distutils`), including proper configuration of compilers and such. I suspect this is for 2 reasons: 1) Historical heritage of NumPy as one of the first C extensions that was widely used enough to try and robustly support a huge variety of platforms; and 2) They use `setup.py` as their main build driver, whereas we use SCons.

I _do not_ intend to put in that much effort for an sdist that may or may not get much use 😹 I think my philosophy will be to support the major compilers on the major platforms (precisely, VS on Windows; Apple's Clang and Homebrew GCC on Mac; and GCC on Linux). People interested in more esoteric options can clone the source code, where `SCons` handles all that business, and/or volunteer to maintain the sdist packaging.

**Comment by ischoegl** [comment]
Thanks for the insights!

> I _do not_ intend to put in that much effort for an sdist that may or may not get much use 😹.

:+1: … regarding approaches (1) or (2). I am less concerned about the user experience as some may prefer everything being handled by the installer with others insisting on their own sundials versions. I’d go with what is easier to implement.

**Comment by bryanwweber** [comment]
For anyone following along, you can now download Linux x86_64 wheels from TestPyPI for Python 3.6, 3.7, 3.8, and 3.9: https://test.pypi.org/project/Cantera/2.6.0a2/
There's also a single macOS ARM wheel for Python 3.9, which is my dev machine. I'd appreciate if anyone with a Linux machine can test the wheels 😄 
```
python -m pip install -i https://test.pypi.org/simple/ Cantera==2.6.0a2
```

Next up are more platforms. By the way, this is all running in GitHub Actions: https://github.com/bryanwweber/cantera/actions/runs/999655230

**Comment by corykinney** [comment]
@bryanwweber Super excited that you're working on this feature. I'm trying to test it on Python 3.9/Windows 10 using the install command listed on the test PyPI page you linked:
```
pip install -i https://test.pypi.org/simple/ Cantera==2.6.0a2
```
but I'm getting the following error:
```
ERROR: Could not find a version that satisfies the requirement Cantera==2.6.0a2 (from versions: none)
ERROR: No matching distribution found for Cantera==2.6.0a2
```

**Comment by bryanwweber** [comment]
@corykinney Per my comment:

> you can now download Linux x86_64 wheels

only Linux wheels are available for the moment :smiley: I should have wheels for other platforms available later this week, but possibly as soon as today 😲

**Comment by bryanwweber** [comment]
@corykinney Actually, if you go here: https://github.com/bryanwweber/cantera/actions/runs/1008461597 and download the "artifact" at the bottom of the run, that's a zip file that contains wheels for all the major platforms. If you unzip it and point pip at the specific wheel file you want to install (`pip install /the/path/to/the/file.whl`) it should work.

**Comment by corykinney** [comment]
@bryanwweber I noticed you hadn't mentioned anything in your post about it being ready for Windows, but the `Microsoft::Windows` operating systems classifier on the test PyPI page deceived me into thinking it might work 😛 I just tried with the artifact and it worked perfectly!

**Comment by decaluwe** [comment]
🎉  Awesome work, @bryanwweber !

**Comment by bryanwweber** [comment]
@corykinney The wheels for all the platforms should be up on TestPyPI now 😄 🎉

**Comment by corykinney** [comment]
@bryanwweber First question: Is it possible to have the `pip install` automatically install the required dependencies if they're not present? I was testing with an empty venv by running:

```
pip install -i https://test.pypi.org/simple/ Cantera==2.6.0a2
```

as I didn't have any other libraries installed yet in my venv, it first gave the error 

```
ERROR: Could not find a version that satisfies the requirement numpy>=1.12.0 (from cantera) (from versions: 1.9.3)
ERROR: No matching distribution found for numpy>=1.12.0
```

until I installed numpy, and then 

```
ERROR: Could not find a version that satisfies the requirement ruamel.yaml>=0.15.34 (from cantera) (from versions: none)
ERROR: No matching distribution found for ruamel.yaml>=0.15.34
```

until I installed ruamel.yaml. It's only a minor thing, but I think it would be nice if neither library was installed (as opposed to an installation of one of those libraries with a conflicting version requirement) that it would just install the latest version of each automatically. Not sure if there is a standard practice for how these installs work or if there's a reason it doesn't work the way I suggested.

Second question: I attempted to run a simple script after installing from the Test PyPI and noticed that it doesn't install any of the built-in mechanisms that normally come with the Cantera installation. I compared the `site-packages\cantera\data` folders for Cantera installed the normal way and Cantera installed from `pip` and noticed that the latter only had an `__init__.py` whereas the former had about 77 additional `.cti`, `.xml`, and `.yaml` files.

**Comment by bryanwweber** [comment]
Thanks @corykinney!

For the first problem, I bet it's because it's pulling from TestPyPI. I wonder if you also add the regular PyPI as a second index if it would work.

For the second, that's something I need to fix in the builder. Thanks for pointing it out!

**Comment by bryanwweber** [comment]
@corykinney Just to confirm, I was able to resolve your first question by doing:

```
python -m pip install --extra-index-url https://test.pypi.org/simple Cantera==2.6.0a2
```

For the second question, at least on my Mac, I show that all of the YAML files are installed in the `data` directory. I deliberately didn't include the CTI and XML files because we're going to deprecate and remove support for those in the next few versions, and people should be able to switch over to YAML pretty seamlessly.

By the way, you can check what data files are installed with Cantera in the Python interface by doing:

```python
import cantera.data as ctd
ctd.list_data_files()
```
