### ISSUE TITLE
Make species charge an accessible phase property

### ISSUE THREAD

**Issue by decaluwe** [Cantera/enhancements#50]
Make the array of species elementary charges an accessible phase property, e.g. via the Python or Matlab interfaces

At present a user must run through the species and save this variable array external to cantera, similar to: 

```
for j in phase.species_names:
    params['Z_k'][phase.species_index(j)] = phase.species(j).charge
```
It should be relatively straightforward to make this array accessible, similar to `phase.molecular_weights`.

**Motivation**
This has utility in a number of electrochemical applications, where the species charge number is used to relate a species flux to a current density.

**Comment by ischoegl** [comment]
:+1: ... This would also help resolve issues arising when parsing reactions that involve charge  transfer (resolving the issue of currently having to parse twice, see #38).

**Comment by ischoegl** [comment]
@decaluwe ... the implementation is straightforward, as I'm not sure that access to this vector is needed at the C++ level. I pushed Cantera/cantera#862 for discussion; MATLAB can be added in a similar fashion. If this is not what is desired, I'll simply close the PR.

**Comment by ischoegl** [comment]
@decaluwe ... no worries. I closed my PR - the tests can be recycled.
