### ISSUE TITLE
Implement `DustyGas` thermal conductivity

### ISSUE THREAD

**Issue by decaluwe** [Cantera/enhancements#53]
**Abstract**
Cantera's `DustyGas` class currently has no method to calculate the gas-phase thermal conductivity.  

A brief description of the proposed change.
Implement the routine currently used in the `IdealGas` class, or make it accessible to the `DustyGas` class.

**Motivation**
At present, anyone who wants to calculate Dusty Gas Model fluxes _and_ energy flux terms has to create a second, parallel `IdealGas` phase object.  Obviously, this is sub-optimal.

**Possible Solutions**

Two possible solutions come readily to mind:
- Brute force method: copy and paste the ideal gas routine inside the DustyGas class.  
- Elegant method: find a way to use class inheritance to make it accessible.  
I have not looked into how possible the latter is, but I imagine that this will be the eventual solution.

I may do this myself, but it would also be a good "first PR" for some aspiring developer...

**Comment by bryanwweber** [comment]
A rule of thumb that I've used is... when code is duplicated twice, leave it be. When you duplicate it a third time (or more) try to make an abstraction. Since the thermal conductivity code is pretty stable (not likely to be a bug there at this point) and since this would be the second "copy", I'm in favor of the brute-force approach.

**Comment by speth** [comment]
In C++, the `DustyGas` class already provides access to the `GasTransport` object that it uses internally, via the `gasTransport()` method. It doesn't look like that's available in the Python interface, but I don't think that would be too difficult to add.

**Comment by bryanwweber** [comment]
Leaving breadcrumbs: https://github.com/Cantera/cantera/pull/988

**Comment by ischoegl** [comment]
Closed via Cantera/cantera#988
