### ISSUE TITLE
Optional argument for Parameter Uncertainties in Cantera Input Files and Objects

### ISSUE THREAD

**Issue by AdityaSavara** [Cantera/enhancements#62]
**The Goal**
To perform uncertainty informed parameter estimation (conventional and Bayesian) with kinetic  simulations and Cantera.  The suggested solution below would also facilitate  uncertainty quantification of the outputs of Cantera simulations.

**Describe the desired solution**
To include an optional "uncertainty" field in the input files. For example, like this:

1) Is anyone else working on or quite far along in a similar effort? *(I found one parameter optimization thread linked at the bottom of this post, but it's not so general).
2) I have a suggestion/request that the ctml writer and internal objects be expanded to have a new optional term within reactions for parameterUncertainties, like this:

example 1:
```
surface_reaction( "Acetaldehyde-Ce(S) => Acetaldehyde + CeCation(S)",
                  Arrhenius(1.0E13, 0, 67400,
                  coverage = ['Acetaldehyde(S)', 0.0, 0.0, -6000.0], 
                 parameterUncertainties=[2.0,0.0, 10000, 0.1, 0.1, 1000.0])
```

Six parameters, six uncertainties, each representing 1 standard deviation, with the one for the preexponential being after a log transform: log(1.0E13)+/-2.  Or, maybe the recommended syntax would be better like this:  
`reaction( .... , parameterUncertainties ="logA:2.0 b:0.0 E:10000" ) `

The advantage of the 2nd syntax being that people could specify an uncertainty for logA or directly for A (the distinction matters for some cases).

Ideally, in the python version of Cantera we could then do things like this:
reactionObject.rate.parameterUncertainties
reactionObject.parameterUncertainties
reactionObject.parameterUncertainties.E

**Describe alternatives you have considered**
I am currently going forward even without this feature, and will store the uncertainties in an external csv file.  This is not an ideal solution because the cantera cti/ctml/yaml files are essentially like a database storage medium. So right now, to perform the several kinds of analyses I am describing requires a person to make two files, two parsers etc. Uncertainties (typically based on the simple case of 1 standard deviation) are a very general part of modeling, so I think it is a good long-term solution to support including that in the fields when making a reaction.

**Additional context**
This was first posted with more details in the usergroup, and a longer form is posted there.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cantera-users/AU7donb9wp0/cxgZJUfNAwAJ

**Comment by speth** [comment]
With user-specified YAML data fully accessible and modifiable in Python (https://github.com/Cantera/cantera/pull/984, https://github.com/Cantera/cantera/pull/1014, https://github.com/Cantera/cantera/pull/1031), I think we have provided a very flexible interface for this capability.
