### ISSUE TITLE
Blowers-Masel approximation in Cantera

### ISSUE THREAD

**Issue by 12Chao** [Cantera/enhancements#66]
**Abstract**

Blowers-Masel approximation allows Cantera to automatically adjust reaction barrier height when species' enthalpies in a reaction are changed. The using case should be, for example, when the species' enthalpy as a function of surface converage, scaling one catalyst surface to another, performing sensitivity analysis of thermochemistry.

**Motivation**

Describe the need for the proposed change:

Linear scaling relationship as implemented in RMG-Cat allows users to predict the binding energy of intermediate species from one metal surface to another. We can explore the effects of changing energetics of uncertain species by global sensitivity analysis. Besides, to match the simulation results to experimental data, some model fitting and optimization algorithms also involves changing species thermochemistry.  In heterogeneous catalysis, the energies of some adsorbed species change in terms of coverage  and can be modeled by coverage-dependent thermochemistry. 

The aforesaid cases involves changing the enthalpy of one or more species. The barrier height or activation energy of a reaction should be adjusted accordingly when the energetics of a reaction is altered, but there is no correction applied on the activation energy in current implementation.  Blowers-Masel approximation would add a builtin function  <img src="https://render.githubusercontent.com/render/math?math=E_a = f(\Delta H_{rxn})"> in Cantera to correct the activation energy of a reaction when the enthalpies of reactants or products are changed. 

The advantage of applying this approximation is that there are only few variables involved in the new activation energy estimation and it is easy to be implemented. 
 
**Possible Solutions**

The Blowers and Masel expression is:
![image](https://user-images.githubusercontent.com/44850205/94225491-1dc8d400-fec3-11ea-91f0-83ed65688594.png)
and<img src="https://render.githubusercontent.com/render/math?math=w_0"> is, from the derivation which applies to hydrogen transfer reactions, the average of the bond dissociation energy of the bond breaking and that being formed. 
However, the expression is very insensitive to <img src="https://render.githubusercontent.com/render/math?math=w_0"> as long as<img src="https://render.githubusercontent.com/render/math?math=w_0 \ge 2E_a^0">, so we can use an arbitrary high value of <img src="https://render.githubusercontent.com/render/math?math=w_0=1000 kJ/mol">.
<img src="https://render.githubusercontent.com/render/math?math=E_a^0"> is termed the ``intrinsic barrier to reaction'' and will equal the activation energy when <img src="https://render.githubusercontent.com/render/math?math=\Delta H_{rxn} = 0">.

For any  reaction with a known <img src="https://render.githubusercontent.com/render/math?math=E_a"> and <img src="https://render.githubusercontent.com/render/math?math=\Delta H_{rxn}">, we can find the value of <img src="https://render.githubusercontent.com/render/math?math=E_a^0">, and then derive a change in <img src="https://render.githubusercontent.com/render/math?math=E_a"> for any given change in <img src="https://render.githubusercontent.com/render/math?math=\Delta H_{rxn}">. 
(For very exothermic reactions we cannot actually solve for <img src="https://render.githubusercontent.com/render/math?math=E_a^0">, but this doesn't matter because the change in <img src="https://render.githubusercontent.com/render/math?math=E_a^0"> will be zero anyway; likewise for very endothermic reactions <img src="https://render.githubusercontent.com/render/math?math=E_a^0"> is undefined but doesn't matter.)

Examples are provided in figure 1.
![image](https://user-images.githubusercontent.com/44850205/94226208-07237c80-fec5-11ea-9780-7e1f69706e9d.png)

To implement Blowers-Masel in Cantera, the consideration includes:
* description of new parameters in YAML input file
* representation in memory
* for Blowers–Masel, automatic derivation of parameters from existing expressions (<img src="https://render.githubusercontent.com/render/math?math=E_a">, <img src="https://render.githubusercontent.com/render/math?math=\Delta H{rxn}"> → <img src="https://render.githubusercontent.com/render/math?math=E_a^0">)

**References**

Paul Blowers and Rich Masel. Engineering approximations for activation energies in hydrogen transfer reactions. AIChE J., 46(10):2041–2052, 2000. doi: 10.1002/aic.690461015.
Detailed proposal:
[BlowersMaselCantera.pdf](https://github.com/Cantera/enhancements/files/5280607/BlowersMaselCantera.pdf)

**Comment by 12Chao** [comment]
The update about this branch is posted on my [forked branch](https://github.com/12Chao/cantera/tree/b-m_approx). I have written a function to update forward rate coefficient according to the activation energy change for all the elementary reactions in a model currently, next step would be writing a new function to estimate  the activation energy change according to the enthalpy change and link this with the forward rate coefficient.

**Comment by rwest** [comment]
In your pull request to cantera, as well as the docstrings don't forget the documentation files:
- [ ] https://github.com/Cantera/cantera/blob/main/doc/sphinx/yaml/reactions.rst
- [ ] https://github.com/Cantera/cantera/blob/main/doc/sphinx/cython/kinetics.rst

And make a new pull request on https://github.com/Cantera/cantera-website (with appropriate notes like "new in 2.6") 
- [ ] Update https://github.com/Cantera/cantera-website/blob/main/pages/tutorials/yaml/reactions.rst 
- [ ] Update https://github.com/Cantera/cantera-website/blob/main/pages/tutorials/yaml/yaml-format.rst
- [ ] Update https://github.com/Cantera/cantera-website/blob/main/pages/science/reactions.rst

**Comment by ischoegl** [comment]
I believe that's closed via Cantera/cantera#987.

**Comment by 12Chao** [comment]
@ischoegl Thanks for mentioning that , I'm working on some examples of how to use Blowers Masel code in analysis like thermodynamic sensitivity analysis, predicting surface reactions' kinetics when catalyst is changed etc., so I'm not sure if I should keep this open or open a new issue for these example work.

**Comment by speth** [comment]
Let's at least wait until the documentation PR Cantera/cantera-website#140 has been merged to close this.

**Comment by ischoegl** [comment]
Closing as documentation has been merged.
