### ISSUE TITLE
Documentation for Peng-Robinson EoS

### ISSUE THREAD

**Issue by gkogekar** [Cantera/enhancements#68]
**Abstract**

Add relevant documentation for the non-ideal, Peng-Robinson equation of state in the `Science' section of the Cantera website.

**Description**

It will include
1. General introduction to equations of state (ideal and non-ideal EoS)
2. Peng-Robinson EoS for pure species as well as the multi-component mixture
3. Thermodynamic properties based on Peng-Robinson EoS.

**Comment by ischoegl** [comment]
An equivalent section of the YAML documentation is also missing in Cantera/cantera (file `doc/sphinx/yaml/phases.rst`).

**Comment by ischoegl** [comment]
Cantera/cantera#1264 partially addresses this issue in terms of YAML input, but Peng-Robinson (like many other phases) lack documentation in the science section of the website (see #6).

**Comment by ischoegl** [comment]
Closing as this is already addressed by #6.
