### ISSUE TITLE
Overhaul of MATLAB Interface

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#7]
**Is your feature request related to a problem? Please describe**

The existing MATLAB toolbox only implements a subset of Cantera features and is difficult to maintain.

**Describe the desired solution**

Completely replace the existing CLIB solution with a solution where [MATLAB calls Python](https://www.mathworks.com/help/matlab/call-python-libraries.html) instead of a compiled MEX function that is routed through a C layer. This will require a complete rewrite of MATLAB classes to wrap the interface, preferably using the [modern implementation of MATLAB classes](https://www.mathworks.com/help/matlab/matlab_oop/compatibility-with-previous-versions-.html).

**Describe alternatives you have considered**

Continue as is: for the introduction of a new feature, changes are required in CLIB, MEX and MATLAB (with various magic numbers obfuscating what is actually done).

**Additional context**

Python-specific features, e.g. `SolutionArray` would become automatically available to MATLAB, without requiring separate solutions in C++.

**Comment by bryanwweber** [comment]
I'm going to close this in favor of #32 which has more detail from the GSoC ideas page, we well as including the detail from the Roadmap.
