### ISSUE TITLE
Change the default prefix to $CONDA_PREFIX if it is set

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/enhancements#76]
**Abstract**

Conda environments are self-contained package installation locations, including C/C++, Python, and other languages. They support all the usual *nix directories (`share`, `lib`, `include`) etc., and have a similarly appropriate structure for Windows. Under certain conditions, it may make sense to set the `prefix` configuration variable to the `$CONDA_PREFIX` environment variable, which holds the path to the currently activated environment.

**Motivation**

In Cantera/cantera#963, the user is using Anaconda Python to build and install Cantera from source. They attempted to use `sudo scons install` to be able to install, but the `sudo` shell did not inherit the shell environment that Conda uses to activate itself, and the installation failed.

One proposed remedy for this case is to assume that the user would like to install all of the files into their Conda environment. Changing this as a default shouldn't cause any problems, since the Conda environment should already have all of the appropriate folders.

**Possible Solutions**

If this enhancement is approved, the default should be changed only when:

1) `prefix` is not set AND
2) `python_prefix` is not set AND
3) `python_cmd` is not set AND
4) `$CONDA_PREFIX` is set AND
5) the Python running SCons is located in `$CONDA_PREFIX`

**References**

https://github.com/Cantera/cantera/issues/963#issuecomment-774597675

**Comment by speth** [comment]
Regarding the final condition, wouldn't it be sufficient to check if `sys.executable` starts with `$CONDA_PREFIX`? I'm not sure what other indicator we'd have that works well cross-platform and across [ana]conda versions.

**Comment by bryanwweber** [comment]
That's a good point. I was thinking they usually put the string `[Aa]naconda` somewhere in the build information. But I was thinking of that before I edited in the `$CONDA_PREFIX` part, so what you say will probably be better.

**Comment by ischoegl** [comment]
Interesting. I was not aware of an issue here as simply omitting the ‘sudo’ from the install command appears to just work. See my gist on windows conda compilation [here](https://gist.github.com/ischoegl/ab777f871a48d7f40ecc32c1c849faa). Not all the files are in the conda folder (see summary at end of post), but things are clearly stated and important files are probably easier to find than within the conda environment.

**Comment by ischoegl** [comment]
>  I was not aware of an issue here as simply omitting ‘sudo’ from the install command appears to just work. 

While this works on windows (which installs to non-write-protected folders by default), the same is not true for Linux.

**Comment by bryanwweber** [comment]
@ischoegl Sorry, I don't get you... this enhancement would set `prefix=$CONDA_PREFIX` under the conditions listed in the original post, which should resolve the need to use `sudo`.

**Comment by ischoegl** [comment]
> ... which should resolve the need to use `sudo`.

Yes, correct. I meant to say that what I stated in my earlier windows-related post is moot.

**Comment by ischoegl** [comment]
Based on (off-topic) discussion in Cantera/cantera#1158 ... I'm planning to tackle this once that PR is merged.

**Comment by bryanwweber** [comment]
@ischoegl I _think_ this should mostly be orthogonal to that effort, so it can perhaps be tackled in parallel?
