### ISSUE TITLE
Equation based modeling of chemical thermodynamics and kinetics

### ISSUE THREAD

**Issue by chengdi1988** [Cantera/enhancements#78]
## Idea
Explore the possibility to make cantera easier to understand, maintain and extend by means of rewriting part of it using equation based modeling method and software infrastructures such as `Modelica` or [`casadi`](https://web.casadi.org/)

* What problem is it trying to solve?

Chemical thermodynamics and kinetics softwares such as cantera are growing heavier. It is relatively easy to use it, but it is seems not so easy to understand, maintain, extend it or integerate it with other softwares. 

Actually, `cantera` is just a software to solve a well defined DAE or ODE system defined with thoustands of organized parameters, including thermodynamics parameters for each species, kinetic parameters for each reactions, transport properties, mixture rules and reactor network parameters to complete the system. All behind the codes are just algebraic or differential equations, state variables, and parameters.

However, the traditional approach requires the author of the software to convert the equations (without directions) to codes (with directional assignments). It is time comsuming, error-prone and the software maintainance is also a problem because usually the code do not describe itself. 

* What are possible solutions?

A more modern approach is `Equation based modeling`. It describe cyber-physical system as equations, state variables and parameters. The equations are non-directional rather than directional assignment. Then a larger system can be deduced and assembled by internal Computer Algebra Systems (CAS). After that, corresponding codes (standard c codes) necessary for numerical simulation such as RHS terms, analytical Jacobian of RHS terms can be generated, complied and linked automatically. 

Based on exsiting equation based modeling environment such Modelica or CasADi, one can write an converter to transfer information of chemical kinetic equations located in `cantera::Solution` object to Modelica or CasADi models easily. The models are human-readable-text-based description of the corresponding equations. 

The model file can be modified or extended by other collabrators with properly named variables and units, verified by grammar-checkers of Modelica, combined with other equation based models in the same platform or co-simulation with other models with Functional Mock-up Interface.

Modelica or CasADi can use the models to generate numerical codes. The internal CAS will do the algebraic manipulation and simplification, sparse or dense jacobian generation, matrix assemble, numerical code integration and even compliation, linking and running.

I am not very sure which one is better, Modelica is developed for a longer time and the eco-system is more mature. CasADi is better at sparse symbolic matrix manipulation and is capable of generating LLVM-IR code. 

* advantages

I expect it would be much easier to maintain, extend and use the equation based models. For example, to support newer equation of state, to generate sparse jacobian calculation subroutine of arbitary set of state variables, or to generate QSSA source term calculation subroutine. All we need to do is add or modify a few lines and wait for code regeneration. The equation based modeling approach guarantees that the maxwell relationship of thermodynamics are maintained for the new equation of state.

It would be much easier to transplant a kinetics model from one PC to another PC. All need to do the copy the generated c code and recompile and relink it.

* disadvantages
If there is some code generation bug beyond equations level, it is almost impossible to do debug. 

The generated code performance heavily relies on the CAS of equation based modeler and compilers' optimization. It is almost impossible to tune it without dive deep into it.

For very large scale problems, the code generator will generate a very very large source code file.

## Difficulty

Medium

## Required Knowledge

Programming language: Python
Knowledge: Chemical thermodynamics and kinetics, basic understanding of Computer Algebra Systems or Equation based modeling method.

## Mentors
I do know. I think the experienced user or author of OpenModelica or CasADi might be suitable for this.

## References
1. [Modelica by Example](https://mbe.modelica.university/)
2. [casadi website](https://web.casadi.org/)
3. [Helmholtz Energy Transformations of Common Cubic Equations of State for Use with Pure Fluids and Mixtures](https://nvlpubs.nist.gov/nistpubs/jres/121/jres.121.011.pdf)
4. [Functional Mock-up Interface](https://fmi-standard.org/)
5. [A python example based on CasADi](https://gitee.com/cheng-di_admin/ebm-chem/blob/master/fastCHEM%20v6.ipynb)

**Comment by jiweiqi** [comment]
Does Julia meets the requirement of `Equation based modeling`? how about developing a new native Julia code?
I have tried to make one called `Arrhenius.jl` https://github.com/DENG-MIT/Arrhenius.jl.
The initial demo was developed within one day, which I believe thanks to equation-based modeling.

Regarding the discussions here, I feel the discussion for the homogenous reactor is straight forward. But the scenario for the one-dimensional flame is complex since we have to take the discretization into consideration.

**Comment by chengdi1988** [comment]
> Does Julia meets the requirement of `Equation based modeling`? how about developing a new native Julia code?
> I have tried to make one called `Arrhenius.jl` https://github.com/DENG-MIT/Arrhenius.jl.
> The initial demo was developed within one day, which I believe thanks to equation-based modeling.
> 
> Regarding the discussions here, I feel the discussion for the homogenous reactor is straight forward. But the scenario for the one-dimensional flame is complex since we have to take the discretization into consideration.

I am not so familiar with Julia language. But I think your code is really easy to follow.

As far as I know, julia is a new potent language good at numerics. There is a very large set of tools such as ODE/DAE solvers available in julia community. And I am not sure if the julia code is easy to cooperate with other existing codes. The library dependency might become an obstacle. 

There are several ways to do [Automatic differentiation(AD)](http://www.autodiff.org/), one way is tape-based dynamic AD, another one is source code transformation based static AD. According to your benchmark, julia is using tape-based dynamic AD. It runs slowly in the first time, but it it much faster for the second time. It is possible to save the generated `tape` to accelerate next usage. But personally I prefer the second way because it can generate standard source code for cross-platform transplantation.

I do not think julia is a full functional equation based modeling environment. It cannot deduce `x=y^(1/3)` from `y=x^3`.  Usually a CAS is needed to to the work. ForwardDiff is just a technique to get gradient from existing sequence of algebraic operations. To construct a complete equation based modeling environment, we need a CAS system to do some simple deduction and some coloring algorithm to determine the sparse structure of Jacobian matrix for very large mechanism.

1D flame is really complicated in both theory and practice: consistent transport properties, adaptive mesh refinement, incompressible limit, flame anchoring and cold boundary difficulty. I think all we can do first is complete the consistent model of transport properties' calculation.

I am not sure which way is better, modelica-like model is useful, but it might be too restrictive for some high performance applications. There are a lot of numeric tricks in developing chemistry solver to make it runs faster by minimizing computation cost. To mention a few: T-dependent function result caching, species transport properties interpolation, replace `pow(x,y)` by x*x if y is integer two. Those tricks cannot be inplanted into equation-based model directly.

**Comment by jiweiqi** [comment]
Hi @chengdi1988 ,

The discussion of AD depends on the purpose of AD. If the purpose is to generate source code for cross-platform translation, I agree that symbolic derivation should be more efficient. It seems that there is some package in Julia aiming at this purpose, like https://github.com/SciML/ModelingToolkit.jl. For Arrhenius.jl, the goal is to build everything on Julia, so that we can use source-to-source AD to compute any gradient that we want. That's to say, beyond chemistry acceleration, we hope it also help data-driven modeling using differentiable programming.

**Comment by bryanwweber** [comment]
This seems largely outside the scope of Cantera as currently constituted. I don't foresee any progress on this, so I'm going to close it. Thanks for sharing the idea!
