### ISSUE TITLE
extend modify_reaction to work correctly for interfaceReactions 

### ISSUE THREAD

**Issue by AdityaSavara** [Cantera/enhancements#8]
**This should be considered low priority.**

**Is your feature request related to a problem? Please describe**
modify_reaction "executes" for surface reactions, but it does not actually work. Though in many cases, it does crash with an error.
Note: I know this is not critical because one can just make a new cti file entirely, and also because I have checked and the set_multiplier function does execute correctly.

**Describe the desired solution**
It would be great if cantera could get modify_reaction to work with sticking and coverage dependent parameters. (Even better if the species of coverage dependence could be changes this way, too).

**Describe alternatives you have considered**
I have considered simply using the set_multiplier function. While this does work for many cases, it does not fix the issue of coverage dependence, since that is a dynamic quantity during simulatio

**Additional context**
I have attached a zipfile with a python file to run to see the issue.
[surf_pfr_modify_Reaction_Bug.zip](https://github.com/Cantera/cantera/files/3903552/surf_pfr_modify_Reaction_Bug.zip)

**Comment by AdityaSavara** [comment]
@speth  @ischoegl  

I am  not sure if I am missing something. The pull request where this issue is mentioned (https://github.com/Cantera/cantera/pull/1181 ) has been merged into main. I've use pip install cantera --upgrade , on windows, and version 2.6  still seems to have the bug mentioned in this issues card. 

I didn't quite understand the conversation completely, but I think that what @ischoegl wrote on that thread suggests he was not successful in completely solving the underlying issue (yet).  So shouldn't this issues card be re-opened?

**Comment by bryanwweber** [comment]
@AdityaSavara sometimes GitHub is a little aggressive about closing issues that get mentioned in pull requests. If this is still a problem, can you verify that the code you posted in the first comment still reproduces the error and feel free to reopen the issue. Thanks! 😃

**Comment by ischoegl** [comment]
@AdityaSavara ... please make sure to check the behavior for YAML input - as CTI input is deprecated, there is no difference in behavior.

**Comment by speth** [comment]
Using Cantera 2.6.0, I can confirm that changing the coverage dependencies for a surface reaction, created either from CTI or YAML input, affects the reaction rates returned by an `Interface` object as long as the `modify_reaction` method is called afterwards.

**Comment by AdityaSavara** [comment]
@ischoegl @speth @bryanwweber 

Thank you for your responses.  After switching to both a YAML file input and also to the new  "from_yaml" syntax, I was able to get the modify_reaction feature to work correctly for my example.
