### ISSUE TITLE
Enable ‘Discussions’ feature on Cantera/enhancements repo

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#83]
**Abstract**

In the GitHub repository settings, it is possible to enable ‘discussions’ (currently a beta feature), which are described as:

> Discussions is the space for your community to have conversations, ask questions and post answers without opening issues

Some of the available default “Topics” are:

* General
* Ideas
* Q&A
* Show and Tell

Additional categories [can be configured](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository), and items can presumably be moved between issues and discussions.

**Motivation**

The list of ‘issues’ (many of which are discussions anyways) is becoming long, and ’discussions’ would allow to better categorize. That way, enhancement ‘issues’ could become a list of items prioritized for implementation, whereas initial ideas can be started as a ‘discussion’.

**Caveat**

This GitHub feature is still in beta and I have not used it myself before, but I thought it interesting enough to type it up as a new ‘feature request’.

**Comment by speth** [comment]
Honestly, I'd been eyeing GitHub Discussions as an alternative to Google Groups. For that purpose, I'd be a little hesitant about shifting from a platform that Cantera's been using for so long to something that's still in beta. However, I think I like your suggestion of using it for a more limited purpose of expanding the way we use this Enhancements repository. I noticed that it's possible to convert Issues to Discussions, which might be helpful for some of the existing items. I don't know if the reverse is possible, but maybe we wouldn't want that anyway, and it would make sense to start a new enhancement issue summarizing a discussion.

**Comment by bryanwweber** [comment]
I'd be hesitant to get rid of the Google Groups for 2 reasons: 1) Historical search (to the extent that people use it) and 2) the ability to post from any email address, without requiring a GitHub account.

That said, I'm also :+1: to enable discussions on this repo, I agree that it facilitates more of a back-and-forth feel and you can customize the notifications to enable/disable Discussion threads. When I get a few minutes (or if someone else wants to), it'd be good to add something to the README about how to use this repo in light of adding discussions.

**Comment by ischoegl** [comment]
I second both comments; looking forward to 'discussions'.

**Comment by speth** [comment]
I enabled Discussions here. Let's see how it works. https://github.com/Cantera/enhancements/discussions.

**Comment by speth** [comment]
@ischoegl - I have a button for transferring Issues over to Discussions, which keeps the existing comments in tact here. If you want to transfer any of the other Issues you posted to Discussions, let me know.

**Comment by ischoegl** [comment]
I know there’s a button, but I didn’t want to bother more than necessary (had already asked multiple times so I tried something different this time, despite the fact that you guys were very responsive earlier) .... there aren’t any other comments I would like to move at the moment.
