### ISSUE TITLE
A third party package for sensitivity analysis of one-dimensional flame

### ISSUE THREAD

**Issue by jiweiqi** [Cantera/enhancements#89]
**Abstract**

A brief description of the work being done.

Currently, Cantera mainly supports the sensitivity of flame speed although one can potentially utilize it for species sensitivity as well. The sensitivity analysis of steady-state one-dimensional flame are usually efficiently computed using Boundary Value Methods, i.e., \partial F/\partial y * \partial y /\partial p + \partial F / \partial p = 0. We are working on pass the solution from Cantera to Julia package of Arrhenius.jl and leverage Arrhenius.jl for calculating the Jacobians and the sensitivity \partial y /\partial p. In addition, this will support the differentiation of augmented neural network models inside the combustion mechanism by passing the Chemical Reaction Neural Network models into Cantera.

**Motivation**

Describe the need for the work being done:

* What problem is it trying to solve?
Enable an extensible third-party sensitivity analysis package for Cantera's one-dimensional flame.

* Who is affected by the change?

* Why is this a good solution?
Take advantage of Julia's auto-differentiation eco-system. And better integration with modern machine learning algorithms. We have an incoming preprint that details how does the auto-differentiation and machine learning algorithms are coupled with existing combustion models.

**Description**

A detailed description of the work being done. This may include examples of how the new feature will be used, intended use cases, and pseudo-code illustrating its use.

I have already implemented BVP algorithms for ignition. The one-dimensional flame will be similar to the ignition example, but 

* we might have to implement the discretization schemes.
* we might have to implement the PyCall interface with Cantera from Arrhenius.jl.
* we might have to enable building mechanism on the fly.

I am not familiar with numerical schemes for one-dimensional flame, like how does discretization works. Collaborations are much needed and welcomed on implementing the discretization in Arrhenius.jl for calculating the residual F.

**Alternatives**

If any alternative solutions to solving the same problem have been considered, describe them here, and explain why the chosen approach is preferred.

**References**

Links to a development branch in your fork of the Cantera repository, Pull Requests, GitHub Issues, Users' Group topics, or other relevant material.

* [Arrhenius.jl](https://github.com/DENG-MIT/Arrhenius.jl)
* [Example of BVP method for ignition sensitivity](https://github.com/DENG-MIT/ArrheniusActiveSubspace)
* [Chemical Reaction Neural Network](https://github.com/DENG-MIT/CRNN)
* https://github.com/Cantera/enhancements/issues/71

**Comment by ischoegl** [comment]
@jiweiqi ... as Bryan said this looks definitely interesting, but I share his questions about the direction of this effort.

@bryanwweber ... as an alternative, per #83 this may be a candidate for ‘show-and-tell’ discussion threads.

**Comment by bryanwweber** [comment]
@ischoegl good point, it might get more exposure on the UG though

**Comment by jiweiqi** [comment]
Hi @bryanwweber , thanks for your suggestions. I could not propose much on the changes of Cantera since I am not familiar with C++. I agree with you that this discussion is more like an application of Cantera. On the other hand, I think the motivation of this proposal itself might be interested in many Cantera developers, including both Cantera's C++ core functionality and Julia interface.

For instance, the adjoint sensitivity of Cantera's one-dimensional flame should be readily enhanced with the same approach outlined in this proposal, if the mentioned method is correct. The computational cost of sensitivity analysis all of the species profiles are the same as sensitivity analysis for flame speed itself.

I do like the idea of the discussion forum!

**Comment by bryanwweber** [comment]
@jiweiqi Since this isn't a proposal for an enhancement to Cantera specifically, I'm going to close it to keep the issues somewhat organized and actionable for the development team. If you'd like to shift this into a feature request for adjoint sensitivity of species in the 1-D module, in addition to the flame speed, I think that'd be more appropriate and you can feel free to edit and reopen the issue to focus around that.

I see you've also commented on #71, which seems to be similar to this one.
